# YAML configuration for SeedReader, SeedCrawler, and LanguageDetector

# SeedReader configuration
seed_reader:
  input_directory: "input" # Directory containing the input JSON files

# SeedCrawler configuration
seed_crawler:
  max_pages: 100 # Maximum number of pages to crawl
  max_workers: 10 # Maximum number of threads for crawling
  crawl_delay: 0.1 # Delay between each crawling request in seconds
  max_time: 600 # Maximum crawl time in seconds
  to_visit_growth_factor: 60

# LanguageDetector configuration
language_detector:
  model_path: "model_v3.bin" # Path to the FastText model file
  desired_language: "und_Sylo" # Target language code
  minimum_confidence: 0.7 # Minimum confidence score for language detection
  save_text: True

# Output configuration
output:
  directory: "output/final/" # Directory to save output JSON files
  output_file_name: "{language}_crawled_output.json" # Output file pattern
  formated_directory: "output/formatted/"
  formated_file_name: "{language}.json"
  cleaned_directory: "output/robots_filtered"
  text_files_directory: "output/text_files"

# Logging configuration
logging:
  level: "INFO" # Logging level: DEBUG, INFO, WARNING, ERROR
  file_path: "logs/application.log" # Path to the log file

# Progress bar configuration
progress_bar:
  enabled: true # Enable or disable tqdm progress bar

# ThreadPoolExecutor configuration
executor:
  max_workers_reader: 5 # Maximum number of threads for reading data

# URL settings
url_settings:
  max_url_length: 65536 # Maximum URL length allowed
  request_timeout: 10 # Timeout for HTTP requests in seconds

domain_file: "filterlist.txt"

batch_processing:
  enabled: True # Set to true to enable batch processing
  # List of languages to process
  input_labels: [
    "wal_Latn",
    "zai_Latn",
    "mfy_Latn",
    "bcc_Arab",
    "sxb_Latn",
    "skr_Arab",
    "pfl_Latn",
    "blk_Mymr",
    "kpe_Latn",
    "rop_Latn",
    "tuk_Cyrl",
    "shi_Latn",
    "mag_Deva",
    "bin_Latn",
    "jvn_Latn",
    "toi_Latn",
    "suk_Latn",
    "wmw_Latn",
    "gor_Latn",
    "tzo_Latn",
    "rmy_Cyrl",
    "wes_Latn",
    "maa_Latn",
    "new_Deva",
    "mhw_Latn",
    "myv_Cyrl",
    "mqj_Latn",
    "qxl_Latn",
    "ban_Latn",
    "zyb_Latn",
    "lki_Arab",
    "ktz_Latn",
    "nhx_Latn",
    "cak_Latn",
    "nan_Latn",
    "alt_Cyrl",
    "tuk_Arab",
    "ote_Latn",
    "mam_Latn",
    "usp_Latn",
    "csy_Latn",
    "rjs_Deva",
    "crk_Latn",
    "mfq_Latn",
    "bzj_Latn",
    "rar_Latn",
    "dhm_Latn",
    "ngl_Latn",
    "aim_Latn",
    "hne_Deva",
    "kek_Latn",
    "stq_Latn",
    "hac_Arab",
    "lew_Latn",
    "xtm_Latn",
    "moc_Latn",
    "tcz_Latn",
    "ndo_Latn",
    "mni_Mtei",
    "seh_Latn",
    "mwl_Latn",
    "sgw_Ethi",
    "sml_Latn",
    "fue_Latn",
    "mxt_Latn",
    "ikw_Latn",
    "blw_Latn",
    "iba_Latn",
    "nnb_Latn",
    "lif_Limb",
    "ota_Arab",
    "mau_Latn",
    "btx_Latn",
    "nyu_Latn",
    "xsm_Latn",
    "nuj_Latn",
    "hus_Latn",
    "miq_Latn",
    "crs_Latn",
    "lmo_Latn",
    "men_Latn",
    "tel_Latn",
    "mph_Latn",
    "dag_Latn",
    "not_Latn",
    "lud_Latn",
    "jra_Latn",
    "mni_Latn",
    "chu_Cyrl",
    "dng_Cyrl",
    "lmk_Latn",
    "gil_Latn",
    "und_Hung",
    "dak_Latn",
    "nbu_Latn",
    "ctu_Latn",
    "ahk_Latn",
    "tkr_Cyrl",
    "swb_Latn",
    "brx_Deva",
    "dik_Latn",
    "sbd_Latn",
    "eve_Cyrl",
    "mui_Latn",
    "krl_Latn",
    "rmy_Latn",
    "quy_Latn",
    "pms_Latn",
    "mfe_Latn",
    "nyy_Latn",
    "ajz_Latn",
    "way_Latn",
    "pbb_Latn",
    "rtm_Latn",
    "ace_Latn",
    "dyi_Latn",
    "lue_Latn",
    "dje_Latn",
    "sdc_Latn",
    "ncj_Latn",
    "qup_Latn",
    "qvw_Latn",
    "nhi_Latn",
    "mjw_Latn",
    "mip_Latn",
    "abs_Latn",
    "kog_Latn",
    "bho_Deva",
    "wsg_Telu",
    "abk_Cyrl",
    "tar_Latn",
    "xmm_Latn",
    "swg_Latn",
    "fon_Latn",
    "crk_Cans",
    "srn_Latn",
    "pam_Latn",
    "uig_Cyrl",
    "ntu_Latn",
    "esu_Latn",
    "bxr_Cyrl",
    "bis_Latn",
    "syc_Syrc",
    "tgp_Latn",
    "zpm_Latn",
    "dar_Cyrl",
    "trv_Latn",
    "wlx_Latn",
    "kum_Cyrl",
    "tab_Cyrl",
    "kqn_Latn",
    "kri_Latn",
    "lez_Cyrl",
    "top_Latn",
    "ksw_Mymr",
    "yrk_Cyrl",
    "nhe_Latn",
    "shp_Latn",
    "tcy_Knda",
    "sop_Latn",
    "atb_Latn",
    "ltg_Latn",
    "und_Sylo",
    "nnw_Latn",
    "tcs_Latn",
    "cop_Copt",
    "uig_Latn",
    "kaa_Cyrl",
    "zpu_Latn",
    "und_Newa",
    "lia_Latn",
    "mjc_Latn",
    "pnt_Grek",
    "gos_Latn",
    "qvc_Latn",
    "yom_Latn",
    "nbl_Latn",
    "uzs_Arab",
    "mni_Beng",
    "sma_Latn",
    "hnj_Latn",
    "srr_Latn",
    "pcd_Latn",
    "vmw_Latn",
    "snd_Deva",
    "trn_Latn",
    "nsu_Latn",
    "lis_Lisu",
    "sgh_Cyrl",
    "dtp_Latn",
    "kmb_Latn",
    "ady_Cyrl",
    "kua_Latn",
    "atj_Latn",
    "orv_Cyrl",
    "raw_Latn",
    "olo_Latn",
    "pdt_Latn",
    "lzh_Hani",
    "pui_Latn",
    "rcf_Latn",
    "tnr_Latn",
    "yao_Latn",
    "skg_Latn",
    "syl_Beng",
    "rml_Latn",
    "qul_Latn",
    "pmf_Latn",
    "lgg_Latn",
    "ctd_Latn",
    "otd_Latn",
    "dyu_Latn",
    "mal_Latn",
    "lld_Latn",
    "nus_Latn",
    "umb_Latn",
    "guw_Latn",
    "hil_Latn",
    "prg_Latn",
    "pwn_Latn",
    "naq_Latn",
    "ojb_Cans",
    "djk_Latn",
    "niu_Latn",
    "fur_Latn",
    "xmf_Geor",
    "und_Shaw",
    "gag_Latn",
    "nso_Latn",
    "thl_Deva",
    "bts_Latn",
    "wbp_Latn",
    "szl_Latn",
    "bpy_Beng",
    "sid_Latn",
    "cnh_Latn",
    "quz_Latn",
    "cmo_Latn",
    "fuv_Latn",
    "nqo_Nkoo",
    "luo_Latn",
    "zpo_Latn",
    "maz_Latn",
    "poe_Latn",
    "trp_Latn",
    "ext_Latn",
    "mnb_Latn",
    "nog_Cyrl",
    "tvk_Latn",
    "mzn_Arab",
    "kac_Latn",
    "tap_Latn",
    "ikt_Latn",
    "ckm_Latn",
    "bcl_Latn",
    "ann_Latn",
    "ami_Latn",
    "zea_Latn",
    "rmn_Cyrl",
    "dyo_Latn",
    "csb_Latn",
    "bru_Latn",
    "ljp_Latn",
    "kik_Latn",
    "ike_Cans",
    "nfa_Latn",
    "lsi_Latn",
    "tat_Latn",
    "tke_Latn",
    "cor_Latn",
    "lug_Latn",
    "nch_Latn",
    "teo_Latn",
    "kwn_Latn",
    "rue_Cyrl",
    "ses_Latn",
    "tly_Latn",
    "pag_Latn",
    "pmx_Latn",
    "yua_Latn",
    "fij_Latn",
    "xal_Cyrl",
    "chv_Cyrl",
    "mar_Latn",
    "kpv_Cyrl",
    "ava_Cyrl",
    "krc_Cyrl",
    "nzi_Latn",
    "nyn_Latn",
    "mhx_Latn",
    "ium_Latn",
    "fub_Latn",
    "abq_Cyrl",
    "smk_Latn",
    "tah_Latn",
    "bhw_Latn",
    "sat_Latn",
    "nhw_Latn",
    "ktu_Latn",
    "shn_Mymr",
    "rhg_Latn",
    "tob_Latn",
    "rmn_Latn",
    "gug_Latn",
    "vol_Latn",
    "hsb_Latn",
    "min_Latn",
    "amu_Latn",
    "gcf_Latn",
    "ain_Latn",
    "nzm_Latn",
    "dsb_Latn",
    "ast_Latn",
    "und_Dsrt",
    "nia_Latn",
    "fuf_Latn",
    "nmz_Latn",
    "anp_Deva",
    "kjh_Cyrl",
    "bre_Latn",
    "tzh_Latn",
    "bim_Latn",
    "efi_Latn",
    "toj_Latn",
    "cbk_Latn",
    "pjt_Latn",
    "pis_Latn",
    "mup_Deva",
    "knc_Latn",
    "moh_Latn",
    "glv_Latn",
    "ptu_Latn",
    "frr_Latn",
    "bjn_Latn",
    "qub_Latn",
    "koi_Cyrl",
    "omw_Latn",
    "kbd_Cyrl",
    "njn_Latn",
    "qxo_Latn",
    "obo_Latn",
    "rnl_Latn",
    "ojb_Latn",
    "tog_Latn",
    "nhr_Latn",
    "bbc_Latn",
    "non_Latn",
    "mti_Latn",
    "tam_Latn",
    "smn_Latn",
    "pck_Latn",
    "kcg_Latn",
    "lij_Latn",
    "nyk_Latn",
    "pot_Latn",
    "mak_Latn",
    "zom_Latn",
    "pls_Latn",
    "szy_Latn",
    "pma_Latn",
    "tig_Ethi",
    "lfn_Cyrl",
    "xmv_Latn",
    "ccp_Latn",
    "smj_Latn",
    "ksh_Latn",
    "swp_Latn",
    "npy_Latn",
    "zdj_Latn",
    "und_Gran",
    "diq_Latn",
    "aii_Syrc",
    "tlh_Latn",
    "glk_Arab",
    "bew_Latn",
    "rmc_Latn",
    "mnw_Mymr",
    "ron_Cyrl",
    "wbm_Latn",
    "ssg_Latn",
    "csw_Latn",
    "kea_Latn",
    "yrl_Latn",
    "ppk_Latn",
    "shk_Latn",
    "tzm_Tfng",
    "sgs_Latn",
    "djr_Latn",
    "tyv_Cyrl",
    "qug_Latn",
    "mvp_Latn",
    "nah_Latn",
    "tok_Latn",
    "yli_Latn",
    "tll_Latn",
    "lwg_Latn",
    "vep_Latn",
    "kby_Latn",
    "dts_Latn",
    "mic_Latn",
    "kck_Latn",
    "dua_Latn",
    "pan_Latn",
    "fkv_Latn",
    "kab_Latn",
    "war_Latn",
    "inh_Cyrl",
    "mrw_Latn",
    "hmr_Latn",
    "lun_Latn",
    "tkl_Latn",
    "kzj_Latn",
    "cfm_Latn",
    "rad_Latn",
    "yue_Hani",
    "zas_Latn",
    "tsg_Latn",
    "rup_Latn",
    "crl_Cans",
    "ory_Latn",
    "nsn_Latn",
    "mhi_Latn",
    "bal_Arab",
    "otw_Latn",
    "npi_Latn",
    "udm_Cyrl",
    "mkn_Latn",
    "tay_Latn",
    "lbe_Cyrl",
    "oss_Cyrl",
    "mnk_Latn",
    "mas_Latn",
    "ewe_Latn",
    "akb_Latn",
    "spp_Latn",
    "guz_Latn",
    "mns_Cyrl",
    "ibg_Latn",
    "cho_Latn",
    "zyp_Latn",
    "yap_Latn",
    "ceb_Latn",
    "yka_Latn",
    "cos_Latn",
    "nov_Latn",
    "wls_Latn",
    "doi_Deva",
    "lfn_Latn",
    "liv_Latn",
    "ckt_Cyrl",
    "mdf_Cyrl",
    "brh_Arab",
    "bdq_Latn",
    "sgc_Latn",
    "taq_Latn"
]
  cooldown_between_languages: 60 # Seconds to wait between processing each language
