# YAML configuration for SeedReader, SeedCrawler, and LanguageDetector

# SeedReader configuration
seed_reader:
  input_directory: "input" # Directory containing the input JSON files

# SeedCrawler configuration
seed_crawler:
  max_pages: 100 # Maximum number of pages to crawl
  max_workers: 10 # Maximum number of threads for crawling
  crawl_delay: 0.1 # Delay between each crawling request in seconds
  max_time: 600 # Maximum crawl time in seconds
  to_visit_growth_factor: 60

# LanguageDetector configuration
language_detector:
  model_path: "model_v3.bin" # Path to the FastText model file
  desired_language: "bcc_Arab" # Target language code
  minimum_confidence: 0.7 # Minimum confidence score for language detection
  save_text: True

# Output configuration
output:
  directory: "output/final/" # Directory to save output JSON files
  output_file_name: "{language}_crawled_output.json" # Output file pattern
  formated_directory: "output/formatted/"
  formated_file_name: "{language}.json"

# Logging configuration
logging:
  level: "INFO" # Logging level: DEBUG, INFO, WARNING, ERROR
  file_path: "logs/application.log" # Path to the log file

# Progress bar configuration
progress_bar:
  enabled: true # Enable or disable tqdm progress bar

# ThreadPoolExecutor configuration
executor:
  max_workers_reader: 5 # Maximum number of threads for reading data

# URL settings
url_settings:
  max_url_length: 65536 # Maximum URL length allowed
  request_timeout: 10 # Timeout for HTTP requests in seconds

domain_file: "filterlist.txt"

batch_processing:
  enabled: False # Set to true to enable batch processing
  # List of languages to process
  input_labels: [
    # 'chu_Cyrl',
    # 'ccp_Latn',
    # 'crl_Cans',
    # 'crk_Cans',
    # 'ctu_Latn',
    # 'csw_Latn',
    # 'efi_Latn',
    # 'esu_Latn',
    # 'eve_Cyrl',
    # 'ewe_Latn',
    # 'ext_Latn',
    # 'fij_Latn',
    # 'fkv_Latn',
    # 'fon_Latn',
    # 'frr_Latn',
    # 'fub_Latn',
    # 'fue_Latn',
    # 'fuf_Latn',
    # 'fur_Latn',
    # 'fuv_Latn',
    # 'gag_Latn',
    # 'gcf_Latn',
    # 'gil_Latn',
    # 'glk_Arab',
    # 'glv_Latn',
    # 'gor_Latn',
    # 'gos_Latn',
    # 'gul_Latn',
    # 'gug_Latn',
    # 'gul_Latn',
    # 'guw_Latn',
    # 'guz_Latn',
    # 'hac_Arab',
    # 'hil_Latn',
    # 'hmr_Latn',
    # 'hne_Deva',
    # 'hnj_Latn',
    # 'hsb_Latn',
    # 'hus_Latn',
    # 'iba_Latn',
    # 'ibg_Latn',
    # 'ike_Cans',
    # 'ikt_Latn',
    # 'ikw_Latn',
    # 'inh_Cyrl',
    # 'ium_Latn',
    # 'jra_Latn',
    # 'jvn_Latn',
    # 'kaa_Cyrl',
    # 'kab_Latn',
    # 'kac_Latn',
    # 'kbd_Cyrl',
    # 'kby_Latn',
    # 'kcg_Latn',
    # 'kck_Latn',
    # 'kea_Latn',
    # 'kek_Latn',
    # 'kik_Latn',
    # 'kjh_Cyrl',
    # 'kmb_Latn',
    # 'knc_Latn',
    # 'kog_Latn',
    # 'koi_Cyrl',
    # 'kpe_Latn',
    # 'kpv_Cyrl',
    # 'kqn_Latn',
    # 'krc_Cyrl',
    # 'kri_Latn',
    # 'krl_Latn',
    # 'ksh_Latn',
    # 'ksw_Mymr',
    # 'ktu_Latn',
    # 'ktz_Latn',
    # 'kua_Latn',
    # 'kum_Cyrl',
    # 'kwn_Latn',
    # 'kzj_Latn',
    # "dik_Latn",
    # "crh_Latn",
    # "csy_Latn",
    # "dop_Latn",
    # "bzj_Latn",
    # "bxr_Cyrl",
    # "ady_Cyrl",
    # "dis_Latn",
    # "aim_Latn",
    # "ctu_Latn",
    # "dak_Latn",
    # "dar_Cyrl",
    # "alt_Cyrl",
    # "anp_Deva",
    # "dsb_Latn",
    # "ami_Latn",
    # "dje_Latn",
    # "cos_Latn",
    # "abq_Cyrl",
    # "dtp_Latn",
    # "dua_Latn",
    # "chu_Cyrl",
    # "cbk_Latn",
    # "bjn_Latn",
    # "cnh_Latn",
    # "bew_Latn",
    # "bru_Latn",
    # "ccp_Latn",
    # "bcl_Latn",
    # "bis_Latn",
    # "dyo_Latn",
    # "bhw_Latn",
    # "brh_Arab",
    # "dhv_Latn",
    # "bpy_Beng",
    # "bim_Latn",
    # "atb_Latn",
    # "bbc_Latn",
    # "ajz_Latn",
    # "cor_Latn",
    # "dng_Cyrl",
    # "dag_Latn",
    # "dyi_Latn",
    # "ace_Latn",
    # "cfm_Latn",
    # "ctd_Latn",
    # "btx_Latn",
    # "ban_Latn",
    # "dhm_Latn",
    # "ckm_Latn",
    # "atj_Latn",
    # "diq_Latn",
    # "ckt_Cyrl",
    # "amu_Latn",
    # "cop_Copt",
    # "crk_Cans",
    # "abk_Cyrl",
    # "ann_Latn",
    # "bin_Latn",
    # "bre_Latn",
    # "bts_Latn",
    # "djr_Latn",
    # "ava_Cyrl",
    # "cmo_Latn",
    # "dyu_Latn",
    # "blw_Latn",
    # "crk_Latn",
    # "crl_Cans",
    # "akb_Latn",
    # "bdq_Latn",
    # "ain_Latn",
    # "crs_Latn",
    # "cak_Latn",
    # "ast_Latn",
    # "csb_Latn",
    # "bcc_Arab",
    # "abs_Latn",
    # "blk_Mymr",
    # "brx_Deva",
    # "doi_Deva",
    # "djk_Latn",
    # "ceb_Latn",
    # "chv_Cyrl",
    # "cho_Latn",
    # "dts_Latn",
    # "bho_Deva",
    # "aii_Syrc",
    ####"bod_Tibt" too big not low resouce
    ############ Checkpoint: 17 Nov: 00:00 AM
    ############ remaining_cc_list
    # "tke_Latn",
    # "pck_Latn",
    # "sgh_Cyrl",
    # "mup_Deva",
    # "toi_Latn",
    # "xog_Latn",
    # "mni_Mtei",
    # "uig_Latn",
    # "lrc_Arab",
    # "shi_Latn",
    # "njn_Latn",
    # "mie_Latn",
    # "nog_Cyrl",
    # "tly_Latn",
    # "mhx_Latn",
    # "tah_Latn",
    # "mfi_Latn",
    # "tam_Latn",
    # "lis_Lisu",
    # "toj_Latn",
    # "maz_Latn",
    # "otd_Latn",
    # "nfa_Latn",
    # "mnb_Latn",
    # "shu_Arab",
    # "smj_Latn",
    # "snd_Latn",
    # "nyy_Latn",
    # "mqj_Latn",
    # "tat_Latn",
    # "sgw_Ethi",
    # "min_Latn",
    # "quf_Latn",
    # "trv_Latn",
    # "smn_Latn",
    # "lif_Limb",
    # "und_Hung",
    # "nus_Latn",
    # "lij_Latn",
    # "und_Gran",
    # "sgs_Latn",
    # "obo_Latn",
    # "nzi_Latn",
    # "mar_Latn",
    # "rup_Latn",
    # "mkn_Latn",
    # "lia_Latn",
    # "qvi_Latn",
    # "tby_Latn",
    # "nlg_Latn",
    # "nmf_Latn",
    # "pps_Latn",
    # "tzm_Tfng",
    # "nbu_Latn",
    # "rap_Latn",
    # "tog_Latn",
    # "nia_Latn",
    # "pma_Latn",
    # "skr_Arab",
    # "lun_Latn",
    # "srr_Latn",
    # "non_Latn",
    # "tob_Latn",
    # "teo_Latn",
    # "spp_Latn",
    # "omb_Latn",
    # "ots_Latn",
    # "uzs_Arab",
    # "zdj_Latn",
    # "ubr_Latn",
    # "qvw_Latn",
    # "szl_Latn",
    # "xmf_Geor",
    # "syc_Syrc",
    # "qxl_Latn",
    # "ncx_Latn",
    # "mrw_Latn",
    # "ptu_Latn",
    # "prg_Latn",
    # "lki_Arab",
    # "und_Dsrt",
    # "pjt_Latn",
    # "nah_Latn",
    # "mfy_Latn",
    # "mjw_Latn",
    # "taq_Latn",
    # "rtm_Latn",
    # "umb_Latn",
    # "lhi_Latn",
    # "xmv_Latn",
    # "yom_Latn",
    # "yrl_Latn",
    # "mni_Beng",
    # "lmo_Latn",
    # "pfl_Latn",
    # "trp_Latn",
    # "pis_Latn",
    # "tok_Latn",
    # "quw_Latn",
    # "rue_Cyrl",
    # "rcf_Latn",
    # "lfn_Latn",
    # "omw_Latn",
    # "sma_Latn",
    # "wlx_Latn",
    # "rej_Latn",
    # "ron_Cyrl",
    # "lbe_Cyrl",
    # "rmy_Latn",
    # "vep_Latn",
    # "row_Latn",
    # "rml_Latn",
    # "nmz_Latn",
    # "rmc_Latn",
    # "rop_Latn",
    # "sda_Latn",
    # "mfe_Latn",
    # "rar_Latn",
    # "rnl_Latn",
    # "nyk_Latn",
    # "sml_Latn",
    # "nyu_Latn",
    # "pan_Latn",
    # "nov_Latn",
    # "nso_Latn",
    # "pms_Latn",
    # "shk_Latn",
    # "qvc_Latn",
############ Checkpoint: 17 Nov: 11:30 AM
    # "nsu_Latn",
    # "pmx_Latn",
    # "top_Latn",
    # "tnr_Latn",
    # "swb_Latn",
    # "ory_Latn",
    # "myv_Cyrl",
    # "sxb_Latn",
    # "npy_Latn",
    # "nhi_Latn",
    # "luo_Latn",
    # "orv_Cyrl",
    # "niu_Latn",
    # "pag_Latn",
    # "quy_Latn",
    # "swp_Latn",
    # "naq_Latn",
    # "tkr_Cyrl",
    # "ssg_Latn",
    # "uig_Cyrl",
    # "tiv_Latn",
    # "pwn_Latn",
    # "wbp_Latn",
    # "mnk_Latn",
    # "tll_Latn",
    # "yka_Latn",
    # "pnt_Grek",
    # "lgg_Latn",
    # "mti_Latn",
    # "yue_Hani",
    # "mhi_Latn",
    # "ppk_Latn",
    # "pbb_Latn",
    # "war_Latn",
    # "sbd_Latn",
    # "tuk_Cyrl",
    # "mui_Latn",
    # "lsi_Latn",
    # "usp_Latn",
    # "nsn_Latn",
    # "tzo_Latn",
    # "swg_Latn",
    # "mip_Latn",
    # "tcz_Latn",
    # "moh_Latn",
    # "mog_Latn",
    # "nin_Latn",
    # "xsm_Latn",
    # "quh_Latn",
    # "zyp_Latn",
    # "lbk_Latn",
    # "shp_Latn",
    # "tsg_Latn",
    # "sdc_Latn",
    # "sop_Latn",
    # "yao_Latn",
    # "men_Latn",
    # "pam_Latn",
    # "laj_Latn",
    # "mdf_Cyrl",
    # "tcy_Knda",
    # "tsz_Latn",
    # "ntu_Latn",
    # "zom_Latn",
    # "wes_Latn",
    # "nhw_Latn",
    # "stq_Latn",
    # "tap_Latn",
    # "wls_Latn",
    # "nhx_Latn",
    # "sps_Latn",
    # "vmw_Latn",
    # "nnb_Latn",
    # "smk_Latn",
    # "tkl_Latn",
    # "maa_Latn",
    # "mfq_Latn",
    # "lez_Cyrl",
    # "wmw_Latn",
    # "liv_Latn",
    # "quz_Latn",
    # "ltg_Latn",
    # "tar_Latn",
    # "udm_Cyrl",
    # "tcs_Latn",
    # "rhg_Latn",
    # "tab_Cyrl",
    # "srn_Latn",
    # "nnw_Latn",
    # "sgc_Latn",
    # "tig_Ethi",
    # "lld_Latn",
    # "qup_Latn",
    # "und_Sylo",
    # "ngu_Latn",
    # "rmo_Latn",
    # "raw_Latn",
    # "qug_Latn",
    # "not_Latn",
    # "npi_Latn",
    # "mph_Latn",
    # "shn_Mymr",
    # "lwg_Latn",
    # "poe_Latn",
    # "qxo_Latn",
    # "ndo_Latn",
    # "und_Shaw",
    # "rmy_Cyrl",
    # "yua_Latn",
    # "srm_Latn",
    # "mhw_Latn",
    # "vol_Latn",
    # "tay_Latn",
    # "olo_Latn",
    # "wsg_Telu",
    # "nzm_Latn",
    # "xmm_Latn",
    # "sat_Latn",
    # "mak_Latn",
    # "pcd_Latn",
    # "zyb_Latn",
    # "ses_Latn",
    # "otw_Latn",
    # "mns_Cyrl",
    # "lue_Latn",
    # "ljp_Latn",
    # "mnw_Mymr",
    # "nbl_Latn",
    # "oss_Cyrl",
    # "snd_Deva",
    # "und_Newa",
    # "mjc_Latn",
    # "pmf_Latn",
    # "ote_Latn",
    # "ngl_Latn",
    # "pdt_Latn",
    # "mal_Latn",
    # "zam_Latn",
    # "qxn_Latn",
    # "nuj_Latn",
    # "tbz_Latn",
    # "wlv_Latn",
    # "mau_Latn",
    # "ncj_Latn",
    # "mag_Deva",
    # "syl_Beng",
    # "zai_Latn",
    # "suk_Latn",
    # "new_Deva",
    # "lew_Latn",
    # "xtm_Latn",
    # "ojb_Cans",
    # "thl_Deva",
    # "tzh_Latn",
    # "xal_Cyrl",
    # "szy_Latn",
    # "nhe_Latn",
    # "rjs_Deva",
    # "rad_Latn",
    # "nyn_Latn",
    # "lmk_Latn",
    # "lud_Latn",
    # "trn_Latn",
    # "yli_Latn",
    # "wal_Latn",
    # "nij_Latn",
    # "zpu_Latn",
    # "mzn_Arab",
    # "lfn_Cyrl",
    ##### Nov 18 check point. 9:15 AM
    # "mam_Latn",
    # "mas_Latn",
    # "pot_Latn",
    # "zpm_Latn",
    # "pls_Latn",
    # "zas_Latn",
    # "ota_Arab",
    # "lzh_Hani",
    # "rmn_Latn",
    # "yrk_Cyrl",
    # "skg_Latn",
    # "tgp_Latn",
    # "nhr_Latn",
    # "mxt_Latn",
    # "tlh_Latn",
    # "tvk_Latn",
    # "miq_Latn",
    # "yle_Latn",
    # "nan_Latn",
    # "mwl_Latn",
    # "nch_Latn",
    # "wbm_Latn",
    # "yap_Latn",
    # "tel_Latn",
    #### Checkpoint: 
    # "zpo_Latn",
    # "pdc_Latn",
    # "tuk_Arab",
    # "tyv_Cyrl",
    # "nqo_Nkoo",
    # "pui_Latn",
    # "mic_Latn",
    # "rmn_Cyrl",
    # "sid_Latn",
    # "mvp_Latn",
    # "ojb_Latn",
    # "mni_Latn",
    # "trc_Latn",
    # "lug_Latn",
    # "qul_Latn",
    # "moc_Latn",
##### Checkpoint : 18.11.2024 15:07
    #### "qub_Latn", turned out to be religious
    # "seh_Latn",
    # "swc_Latn",
    # "zea_Latn",
    # "way_Latn"
]
  cooldown_between_languages: 60 # Seconds to wait between processing each language
