# YAML configuration for SeedReader, SeedCrawler, and LanguageDetector

# SeedReader configuration
seed_reader:
  input_directory: "input" # Directory containing the input JSON files

# SeedCrawler configuration
seed_crawler:
  max_pages: 100 # Maximum number of pages to crawl
  max_workers: 10 # Maximum number of threads for crawling
  crawl_delay: 0.1 # Delay between each crawling request in seconds
  max_time: 600 # Maximum crawl time in seconds
  to_visit_growth_factor: 50

# LanguageDetector configuration
language_detector:
  model_path: "model_v3.bin" # Path to the FastText model file
  desired_language: "abk_Cyrl" # Target language code
  minimum_confidence: 0.7 # Minimum confidence score for language detection
  save_text: True

# Output configuration
output:
  directory: "output/final/" # Directory to save output JSON files
  output_file_name: "{language}_crawled_output.json" # Output file pattern

# Logging configuration
logging:
  level: "INFO" # Logging level: DEBUG, INFO, WARNING, ERROR
  file_path: "logs/application.log" # Path to the log file

# Progress bar configuration
progress_bar:
  enabled: true # Enable or disable tqdm progress bar

# ThreadPoolExecutor configuration
executor:
  max_workers_reader: 5 # Maximum number of threads for reading data

# URL settings
url_settings:
  max_url_length: 65536 # Maximum URL length allowed
  request_timeout: 10 # Timeout for HTTP requests in seconds

domain_file: "filterlist.txt"