# YAML configuration for SeedReader, SeedCrawler, and LanguageDetector

# SeedReader configuration
seed_reader:
  input_directory: "input" # Directory containing the input JSON files

# SeedCrawler configuration
seed_crawler:
  max_pages: 100 # Maximum number of pages to crawl
  max_workers: 10 # Maximum number of threads for crawling
  crawl_delay: 0.1 # Delay between each crawling request in seconds
  max_time: 600 # Maximum crawl time in seconds
  to_visit_growth_factor: 60

# LanguageDetector configuration
language_detector:
  model_path: "model_v3.bin" # Path to the FastText model file
  desired_language: "abk_Cyrl" # Target language code
  minimum_confidence: 0.7 # Minimum confidence score for language detection
  save_text: True

# Output configuration
output:
  directory: "output/final/" # Directory to save output JSON files
  output_file_name: "{language}_crawled_output.json" # Output file pattern
  formated_directory: "output/formatted/"
  formated_file_name: "{language}.json"

# Logging configuration
logging:
  level: "INFO" # Logging level: DEBUG, INFO, WARNING, ERROR
  file_path: "logs/application.log" # Path to the log file

# Progress bar configuration
progress_bar:
  enabled: true # Enable or disable tqdm progress bar

# ThreadPoolExecutor configuration
executor:
  max_workers_reader: 5 # Maximum number of threads for reading data

# URL settings
url_settings:
  max_url_length: 65536 # Maximum URL length allowed
  request_timeout: 10 # Timeout for HTTP requests in seconds

domain_file: "filterlist.txt"

batch_processing:
  enabled: True # Set to true to enable batch processing
  input_labels: [
  #  "dik_Latn",
  #  "crh_Latn",
  #  "csy_Latn",
    "dop_Latn",
    "bzj_Latn",
    "bxr_Cyrl",
    "ady_Cyrl",
    "dis_Latn",
    "aim_Latn",
    "ctu_Latn",
    "dak_Latn",
    "dar_Cyrl",
    "alt_Cyrl",
    "anp_Deva",
    "dsb_Latn",
    "ami_Latn",
    "dje_Latn",
    "cos_Latn",
    "abq_Cyrl",
    "dtp_Latn",
    "dua_Latn",
    "chu_Cyrl",
    "cbk_Latn",
    "bjn_Latn",
    "cnh_Latn",
    "bew_Latn",
    "bru_Latn",
    "ccp_Latn",
    "bcl_Latn",
    "bis_Latn",
    "dyo_Latn",
    "bhw_Latn",
    "brh_Arab",
    "dhv_Latn",
    "bpy_Beng",
    "bim_Latn",
    "atb_Latn",
    "bbc_Latn",
    "ajz_Latn",
    "cor_Latn",
    "dng_Cyrl",
    "dag_Latn",
    "dyi_Latn",
    "ace_Latn",
    "cfm_Latn",
    "ctd_Latn",
    "btx_Latn",
    "ban_Latn",
    "dhm_Latn",
    "ckm_Latn",
    "atj_Latn",
    "diq_Latn",
    "ckt_Cyrl",
    "amu_Latn",
    "cop_Copt",
    "crk_Cans",
    "abk_Cyrl",
    "ann_Latn",
    "bin_Latn",
    "bre_Latn",
    "bts_Latn",
    "djr_Latn",
    "ava_Cyrl",
    "cmo_Latn",
    "dyu_Latn",
    "blw_Latn",
    "crk_Latn",
    "crl_Cans",
    "akb_Latn",
    "bdq_Latn",
    "ain_Latn",
    "crs_Latn",
    "cak_Latn",
    "div_Thaa",
    "ast_Latn",
    "csb_Latn",
    "bal_Arab",
    "abs_Latn",
    "blk_Mymr",
    "brx_Deva",
    "doi_Deva",
    "djk_Latn",
    "ceb_Latn",
    "chv_Cyrl",
    "cho_Latn",
    "dts_Latn",
    "bho_Deva",
    "aii_Syrc",
    "bod_Tibt"
] # List of languages to process
  cooldown_between_languages: 60 # Seconds to wait between processing each language
