# YAML configuration for SeedReader, SeedCrawler, and LanguageDetector

# SeedReader configuration
seed_reader:
  input_directory: "crawler_input" # Directory containing the input JSON files

# SeedCrawler configuration
seed_crawler:
  max_pages: 100 # Maximum number of pages to crawl
  max_workers: 10 # Maximum number of threads for crawling
  crawl_delay: 0.1 # Delay between each crawling request in seconds
  max_time: 600 # Maximum crawl time in seconds
  to_visit_growth_factor: 60

# LanguageDetector configuration
language_detector:
  model_path: "model_v3.bin" # Path to the FastText model file
  desired_language: "bpy_Beng" # Target language code
  minimum_confidence: 0.7 # Minimum confidence score for language detection
  save_text: True

# Output configuration
output:
  directory: "output/crawled/" # Directory to save output JSON files
  output_file_name: "{language}_crawled_output.json" # Output file pattern
  formated_directory: "output/formatted/"
  formated_file_name: "{language}.json"
  cleaned_directory: "output/robots_filtered"
  text_files_directory: "output/text_files"

# Logging configuration
logging:
  level: "INFO" # Logging level: DEBUG, INFO, WARNING, ERROR
  file_path: "logs/application.log" # Path to the log file

# Progress bar configuration
progress_bar:
  enabled: True # Enable or disable tqdm progress bar

# ThreadPoolExecutor configuration
executor:
  max_workers_reader: 5 # Maximum number of threads for reading data

# URL settings
url_settings:
  max_url_length: 65536 # Maximum URL length allowed
  request_timeout: 10 # Timeout for HTTP requests in seconds

domain_file: "metadata/filterlist.txt"

batch_processing:
  enabled: True # Set to true to enable batch processing
  # List of languages to process
  input_labels: [
  "abk_Cyrl",
  "abq_Cyrl",
  "abs_Latn",
  "ace_Latn",
  "ady_Cyrl",
  "ahk_Latn",
  "aii_Syrc",
  "ain_Latn",
  "ajz_Latn",
  "akb_Latn",
  "alt_Cyrl",
  "ami_Latn",
  "amu_Latn",
  "ann_Latn",
  "anp_Deva",
  "ast_Latn",
  "atb_Latn",
  "atj_Latn",
  "ava_Cyrl",
  "ban_Latn",
  "bbc_Latn",
  "bcc_Arab",
  "bcl_Latn",
  "bdq_Latn",
  "bew_Latn",
  "bho_Deva",
  "bim_Latn",
  "bin_Latn",
  "bis_Latn",
  "bjn_Latn",
  "blk_Mymr",
  "blw_Latn",
  "bpy_Beng",
  "bre_Latn",
  "brh_Arab",
  "bru_Latn",
  "brx_Deva",
  "bts_Latn",
  "btx_Latn",
  "bxr_Cyrl",
  "bzj_Latn",
  "cak_Latn",
  "cbk_Latn",
  "ccp_Latn",
  "ceb_Latn",
  "cfm_Latn",
  "cho_Latn",
  "chu_Cyrl",
  "chv_Cyrl",
  "ckm_Latn",
  "ckt_Cyrl",
  "cmo_Latn",
  "cnh_Latn",
  "cop_Copt",
  "cor_Latn",
  "cos_Latn",
  "crk_Cans",
  "crk_Latn",
  "crl_Cans",
  "crs_Latn",
  "csb_Latn",
  "csw_Latn",
  "csy_Latn",
  "ctd_Latn",
  "ctu_Latn",
  "dag_Latn",
  "dak_Latn",
  "dar_Cyrl",
  "dik_Latn",
  "diq_Latn",
  "dje_Latn",
  "djk_Latn",
  "djr_Latn",
  "dng_Cyrl",
  "doi_Deva",
  "dsb_Latn",
  "dtp_Latn",
  "dts_Latn",
  "dua_Latn",
  "dyi_Latn",
  "dyo_Latn",
  "efi_Latn",
  "esu_Latn",
  "eve_Cyrl",
  "ewe_Latn",
  "ext_Latn",
  "fij_Latn",
  "fkv_Latn",
  "fon_Latn",
  "frr_Latn",
  "fub_Latn",
  "fuf_Latn",
  "fur_Latn",
  "fuv_Latn",
  "gag_Latn",
  "gcf_Latn",
  "gil_Latn",
  "glk_Arab",
  "glv_Latn",
  "gor_Latn",
  "gos_Latn",
  "gug_Latn",
  "guw_Latn",
  "guz_Latn",
  "hac_Arab",
  "hil_Latn",
  "hmr_Latn",
  "hne_Deva",
  "hnj_Latn",
  "hsb_Latn",
  "hus_Latn",
  "iba_Latn",
  "ibg_Latn",
  "ike_Cans",
  "ikt_Latn",
  "ikw_Latn",
  "inh_Cyrl",
  "ium_Latn",
  "jra_Latn",
  "jvn_Latn",
  "kaa_Cyrl",
  "kab_Latn",
  "kac_Latn",
  "kbd_Cyrl",
  "kby_Latn",
  "kcg_Latn",
  "kck_Latn",
  "kea_Latn",
  "kek_Latn",
  "kik_Latn",
  "kjh_Cyrl",
  "kmb_Latn",
  "knc_Latn",
  "kog_Latn",
  "koi_Cyrl",
  "kpe_Latn",
  "kpv_Cyrl",
  "kqn_Latn",
  "krc_Cyrl",
  "kri_Latn",
  "krl_Latn",
  "ksh_Latn",
  "ksw_Mymr",
  "ktu_Latn",
  "ktz_Latn",
  "kua_Latn",
  "kum_Cyrl",
  "kwn_Latn",
  "kzj_Latn",
  "lbe_Cyrl",
  "lew_Latn",
  "lez_Cyrl",
  "lfn_Cyrl",
  "lfn_Latn",
  "lgg_Latn",
  "lia_Latn",
  "lif_Limb",
  "lij_Latn",
  "lis_Lisu",
  "liv_Latn",
  "ljp_Latn",
  "lki_Arab",
  "lld_Latn",
  "lmk_Latn",
  "lmo_Latn",
  "lsi_Latn",
  "ltg_Latn",
  "lug_Latn",
  "lun_Latn",
  "luo_Latn",
  "lwg_Latn",
  "maa_Latn",
  "mag_Deva",
  "mak_Latn",
  "mal_Latn",
  "mam_Latn",
  "mar_Latn",
  "mas_Latn",
  "mau_Latn",
  "maz_Latn",
  "mdf_Cyrl",
  "men_Latn",
  "mfe_Latn",
  "mfq_Latn",
  "mfy_Latn",
  "mhi_Latn",
  "mhw_Latn",
  "mhx_Latn",
  "mic_Latn",
  "min_Latn",
  "mip_Latn",
  "miq_Latn",
  "mjc_Latn",
  "mjw_Latn",
  "mkn_Latn",
  "mnb_Latn",
  "mni_Beng",
  "mni_Latn",
  "mni_Mtei",
  "mnk_Latn",
  "mns_Cyrl",
  "mnw_Mymr",
  "moc_Latn",
  "moh_Latn",
  "mph_Latn",
  "mqj_Latn",
  "mrw_Latn",
  "mui_Latn",
  "mup_Deva",
  "mvp_Latn",
  "mwl_Latn",
  "mxt_Latn",
  "myv_Cyrl",
  "mzn_Arab",
  "nah_Latn",
  "nan_Latn",
  "naq_Latn",
  "nbl_Latn",
  "nbu_Latn",
  "nch_Latn",
  "ncj_Latn",
  "ndo_Latn",
  "new_Deva",
  "nhi_Latn",
  "nhw_Latn",
  "nhx_Latn",
  "nia_Latn",
  "niu_Latn",
  "njn_Latn",
  "nmz_Latn",
  "nnb_Latn",
  "nnw_Latn",
  "nog_Cyrl",
  "non_Latn",
  "not_Latn",
  "nov_Latn",
  "npi_Latn",
  "npy_Latn",
  "nqo_Nkoo",
  "nso_Latn",
  "nsu_Latn",
  "nuj_Latn",
  "nus_Latn",
  "nyk_Latn",
  "nyn_Latn",
  "nzi_Latn",
  "nzm_Latn",
  "obo_Latn",
  "ojb_Latn",
  "olo_Latn",
  "omw_Latn",
  "orv_Cyrl",
  "ory_Latn",
  "oss_Cyrl",
  "ota_Arab",
  "otd_Latn",
  "ote_Latn",
  "otw_Latn",
  "pag_Latn",
  "pam_Latn",
  "pan_Latn",
  "pbb_Latn",
  "pcd_Latn",
  "pck_Latn",
  "pdt_Latn",
  "pfl_Latn",
  "pis_Latn",
  "pjt_Latn",
  "pls_Latn",
  "pma_Latn",
  "pmf_Latn",
  "pms_Latn",
  "pmx_Latn",
  "pnt_Grek",
  "poe_Latn",
  "pot_Latn",
  "ppk_Latn",
  "prg_Latn",
  "ptu_Latn",
  "pui_Latn",
  "pwn_Latn",
  "qub_Latn",
  "qug_Latn",
  "qup_Latn",
  "quy_Latn",
  "quz_Latn",
  "qvc_Latn",
  "qvw_Latn",
  "qxl_Latn",
  "qxo_Latn",
  "rad_Latn",
  "rar_Latn",
  "raw_Latn",
  "rcf_Latn",
  "rjs_Deva",
  "rmc_Latn",
  "rml_Latn",
  "rmn_Cyrl",
  "rmn_Latn",
  "rmy_Cyrl",
  "rmy_Latn",
  "rnl_Latn",
  "ron_Cyrl",
  "rop_Latn",
  "rtm_Latn",
  "rue_Cyrl",
  "rup_Latn",
  "sat_Latn",
  "sbd_Latn",
  "sdc_Latn",
  "ses_Latn",
  "sgc_Latn",
  "sgh_Cyrl",
  "sgs_Latn",
  "shi_Latn",
  "shk_Latn",
  "shn_Mymr",
  "shp_Latn",
  "sid_Latn",
  "skr_Arab",
  "sma_Latn",
  "smj_Latn",
  "smk_Latn",
  "sml_Latn",
  "smn_Latn",
  "snd_Deva",
  "sop_Latn",
  "spp_Latn",
  "srn_Latn",
  "srr_Latn",
  "ssg_Latn",
  "stq_Latn",
  "suk_Latn",
  "swg_Latn",
  "swp_Latn",
  "sxb_Latn",
  "syc_Syrc",
  "syl_Beng",
  "szl_Latn",
  "szy_Latn",
  "tab_Cyrl",
  "tah_Latn",
  "tam_Latn",
  "tar_Latn",
  "tat_Latn",
  "tay_Latn",
  "tcy_Knda",
  "tcz_Latn",
  "tel_Latn",
  "teo_Latn",
  "tgp_Latn",
  "thl_Deva",
  "tig_Ethi",
  "tkl_Latn",
  "tkr_Cyrl",
  "tlh_Latn",
  "tll_Latn",
  "tly_Latn",
  "tnr_Latn",
  "tob_Latn",
  "toi_Latn",
  "toj_Latn",
  "tok_Latn",
  "top_Latn",
  "trn_Latn",
  "trp_Latn",
  "trv_Latn",
  "tsg_Latn",
  "tuk_Arab",
  "tuk_Cyrl",
  "tyv_Cyrl",
  "tzh_Latn",
  "tzm_Tfng",
  "tzo_Latn",
  "udm_Cyrl",
  "uig_Cyrl",
  "uig_Latn",
  "und_Dsrt",
  "und_Gran",
  "und_Hung",
  "und_Newa",
  "und_Shaw",
  "und_Sylo",
  "uzs_Arab",
  "vep_Latn",
  "vmw_Latn",
  "vol_Latn",
  "wal_Latn",
  "war_Latn",
  "way_Latn",
  "wbm_Latn",
  "wbp_Latn",
  "wes_Latn",
  "wls_Latn",
  "wlx_Latn",
  "wsg_Telu",
  "xal_Cyrl",
  "xmf_Geor",
  "xmm_Latn",
  "xmv_Latn",
  "xtm_Latn",
  "yap_Latn",
  "yka_Latn",
  "yli_Latn",
  "yom_Latn",
  "yrk_Cyrl",
  "yrl_Latn",
  "yua_Latn",
  "yue_Hani",
  "zai_Latn",
  "zdj_Latn",
  "zea_Latn",
  "zom_Latn",
  "zpm_Latn",
  "zpo_Latn",
  "zpu_Latn",
  "zyb_Latn",
  "zyp_Latn"
]
  cooldown_between_languages: 60 # Seconds to wait between processing each language
